# Generated by Django 5.0.6 on 2024-08-05 11:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('max_players', models.IntegerField(default=4)),
                ('loser_rule', models.IntegerField(default=4)),
                ('game_amount', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('room_max_players', models.IntegerField(default=4)),
                ('room_loser_rule', models.IntegerField(default=4)),
                ('room_game_amount', models.IntegerField(default=10)),
                ('date_time', models.DateTimeField()),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['join_order'],
            },
        ),
    ]
