# Generated by Django 5.0.6 on 2024-08-05 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roombase',
            name='losers',
            field=models.ManyToManyField(blank=True, related_name='losers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roombase',
            name='room_players',
            field=models.ManyToManyField(blank=True, related_name='room_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roombase',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='winners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomplayer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='rooms', through='games.RoomPlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='roomplayer',
            unique_together={('room', 'player')},
        ),
    ]
